// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjhgepcjusoenxoeohkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqaGdlcGNqdXNvZW54b2VvaGtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MzU2NTEsImV4cCI6MjA2NzExMTY1MX0.y0TqPnfAl0tsGllHlEKWlxqSw92shtskvxb4bvPot_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});